name: pulse_dial_donor
description: "Pulse Dial: Native Geofenced Emergency Donor Android Client"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.0
  qr_flutter: ^4.1.0
  geolocator: ^11.0.0
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  http: ^1.2.0
  web_socket_channel: ^2.4.1
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
